### ISSUE TITLE
7-day notice not found

### ISSUE THREAD

**Issue by hazrenvargas** [tastybento/askygrid#13]
I have submitted a 7-day notice for 20161 St Aubin St. Tenant states she received the notice yesterday and when I emailed Lisa to request a court date she could not find the file. I checked and could not find one also. Please fix the issue A.S.A.P.

**Comment by Lmmb74** [comment]
What does that have to do with this plugin?

**Comment by hazrenvargas** [comment]
Lisa could not unable to print this notice – there is no demand uploaded under Notice Filed.

**Comment by tastybento** [comment]
This is a software development website.
