### ISSUE TITLE
Water not ignoring gravity

### ISSUE THREAD

**Issue by tylerking** [tastybento/askygrid#2]
Some of the water blocks don't ignore gravity by default and some do. Here is a screenshot:

https://imgur.com/a/6WXkE

**Comment by tylerking** [comment]
I regenerated the world and this was no longer happening so this could of been a fluke.

Edit: So it seems it takes about a minute before the water starts to fall in random spots.

**Comment by tastybento** [comment]
I saw this too. Try the new version. Let's monitor.

**Comment by tylerking** [comment]
I tried the latest release earlier today and this was still happening: https://imgur.com/a/5nKEM

**Comment by tastybento** [comment]
Yep. But try the latest one I just uploaded. I've made quite a few changes. Let's see if it still happens.

**Comment by tylerking** [comment]
Tried the latest release and its unfortunately still happening: https://imgur.com/a/woIKd

**Comment by tastybento** [comment]
I think this is from ice melting! Try and remove ICE from the config and see what happens.

**Comment by tastybento** [comment]
Yep, it' ice.
