### ISSUE TITLE
The /asg cp command not working

### ISSUE THREAD

**Issue by tylerking** [tastybento/askygrid#3]
The /asg controlpanel and /asg cp commands do not work. I didn't see a config for the control panel either so I'm guessing that feature hasn't been implemented yet but wanted to put it on the radar.

**Comment by tastybento** [comment]
Try this updated release. I recommend a world reset. 
https://github.com/tastybento/askygrid/releases/tag/V2.0debug

Actually cp is not planned to be in the game.
